[workspace]
members = ["slate-verifier"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/Slate-Org/slate"

[workspace.dependencies]
alloy-primitives = "1.5.7"
alloy-sol-types = "1.5.7"
stylus-sdk = "0.10.9"

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = 3
